version: "3.8"

services:
  kafka:
    image: qixxiq/bluesqrl-kafka:latest
    restart: always
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - kafka-data:/kafka-logs
  bluesqrl:
    image: qixxiq/bluesqrl:latest
    restart: always
    command: >
      ./bin/dev feed-to-kafka --kafka=kafka:9092
  process-feed:
    image: qixxiq/bluesqrl:latest
    restart: always
    command: >
      ./bin/dev process-feed --kafka=kafka:9092
  bigquery-insert:
    image: qixxiq/bluesqrl:latest
    restart: always
    command: >
      ./bin/dev bigquery-insert --kafka=kafka:9092

volumes:
  kafka-data:
