version: "3.8"

services:
  kafka:
    image: us-east4-docker.pkg.dev/josh-personal-201806/docker-dev/dev-kafka:latest
    restart: always
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - kafka-data:/kafka-logs
  bluesqrl:
    image: us-east4-docker.pkg.dev/josh-personal-201806/docker-dev/bluesqrl:latest
    restart: always
    command: >
      ./bin/dev feed-to-kafka --kafka=kafka:9092

volumes:
  kafka-data:
