#!/bin/bash
set -xeo pipefail
cd "$(dirname $0)"
mkdir -p ./build
rsync -av ../../sqrl/packages build/sqrl --exclude node_modules
docker build -t qixxiq/bluesqrl:latest .
docker push qixxiq/bluesqrl:latest
